### ISSUE TITLE
Searching caller for proper argument hinting

### ISSUE THREAD

**Issue by pohmelie** [pohmelie/cuda_tern#1]
``` js
function yoba(a, b) {
    return a + b;
}

function foo(x) {
    return x;
}

yoba(foo(yoba(1, 2))|, 3)
```

`|` is cursor position.
So, on `ctrl-shift-space` there should be hint about `yoba` arguments. To achieve this we should get token at caret position. And move "left" through tokens to find first `yoba` call.

For this cuda API should return index of token on `get_token` call too.

**Comment by Alexey-T** [comment]
Can do it w/out changin API. get all tokens (TOKEN_INDEX from 0...) until u get token after NPos. and it is fast
