### ISSUE TITLE
Rework get filename

### ISSUE THREAD

**Issue by Alexey-T** [pohmelie/cuda_tern#12]
now get of filename works for Tern tests, dont work for 1 file test.
How to get full filename from tern?

```
    # Tern gives "test/reload.js" while we edit "reload.js" in "test"
    dirname = os.path.dirname(os.path.dirname(ed.get_filename()))
    if dirname:
        filename = os.path.join(dirname, filename)
```

**Comment by pohmelie** [comment]
Don't get why there is two `os.path.dirname` in code.

**Comment by Alexey-T** [comment]
i will rework this. two since I tested Tern test js's.

**Comment by Alexey-T** [comment]
Is it Ok now. i see goto now works with manu files
@pohmelie

**Comment by pohmelie** [comment]
I don't get what was wrong?

**Comment by Alexey-T** [comment]
I see now it is working ok
