### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by Alexey-T** [pohmelie/cuda_tern#13]
can we pass TERN_TIMEOUT to tern too?
@pohmelie

**Comment by pohmelie** [comment]
Definitely can, will fix this ASAP.

**Comment by Alexey-T** [comment]
Better del param then?

```
opener.open(..timeout=TERN_TIMEOUT)
```

**Comment by pohmelie** [comment]
Probably, I think it does not matter who will trigger timeout.

**Comment by Alexey-T** [comment]
okey, removed.
